name: Open Docker Builder

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Dotenv Action
      uses: falti/dotenv-action@v1.0.4
      with:
        path: .env
        log-variables: true
        mask-variables: false
        export-variables: true
        keys-case: bypass
    # - name: Free Disk Space (Ubuntu)
    #   uses: jlumbroso/free-disk-space@main
    #   with:
    #     tool-cache: false
    #     android: true
    #     dotnet: true
    #     haskell: true
    #     large-packages: true
    #     swap-storage: true
    - name: Prepare Dockerfile
      run: |
        wget $DOCKERFILE -O Dockerfile
    - name: Login to Container Registry
      uses: docker/login-action@v2
      with:
        registry: $REGISTRY
        username: ${{secrets.DOCKER_USER}}
        password: ${{secrets.DOCKER_PASS}}
    - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: $REGISTRY/$REGISTRY_NS/$TAG_NAME:$TAG_VERSION