name: Open Docker Builder

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Dotenv Action
      uses: falti/dotenv-action@v1.0.4
      with:
        path: .env
        log-variables: true
        mask-variables: false
        export-variables: true
        keys-case: bypass
    - name: Free disk space
      run: |
        df -h
        sudo apt-get remove -y azure-cli google-cloud-sdk hhvm google-chrome-stable firefox powershell
        sudo apt-get autoremove -y
        sudo apt-get clean
        sudo swapoff -a
        sudo rm -f /swapfile
        docker rmi $(docker image ls -aq)
        df -h
    - name: Build docker image
      run: |
        wget $DOCKERFILE -O Dockerfile
        docker build -t $REGISTRY/$REGISTRY_NS/$TAG_NAME:$TAG_VERSION -f Dockerfile .
    - name: Push docker image
      run: |
        docker login -u ${{secrets.DOCKER_USER}} -p ${{secrets.DOCKER_PASS}} $REGISTRY
        docker push $REGISTRY/$REGISTRY_NS/$TAG_NAME:$TAG_VERSION
        docker logout $REGISTRY