name: Open Docker Builder

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Dotenv Action
      uses: falti/dotenv-action@v1.0.4
      with:
        path: .env
        log-variables: true
        mask-variables: false
        export-variables: true
        keys-case: bypass
    - name: Free Disk Space (Ubuntu)
      uses: jlumbroso/free-disk-space@main
      with:
        # this might remove tools that are actually needed,
        # if set to "true" but frees about 6 GB
        tool-cache: false
        # all of these default to true, but feel free to set to
        # "false" if necessary for your workflow
        android: true
        dotnet: true
        haskell: true
        large-packages: true
        swap-storage: true
    - name: Build docker image
      run: |
        wget $DOCKERFILE -O Dockerfile
        docker build -t $REGISTRY/$REGISTRY_NS/$TAG_NAME:$TAG_VERSION -f Dockerfile .
    - name: Push docker image
      run: |
        docker login -u ${{secrets.DOCKER_USER}} -p ${{secrets.DOCKER_PASS}} $REGISTRY
        docker push $REGISTRY/$REGISTRY_NS/$TAG_NAME:$TAG_VERSION
        docker logout $REGISTRY