name: Open Docker Builder

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Dotenv Action
      uses: falti/dotenv-action@v1.0.4
      with:
        path: .env
        log-variables: true
        mask-variables: false
        export-variables: true
        keys-case: bypass
    - name: Print
      run: |
        echo $REGISTRY
